# Use official Node.js LTS image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --productionyes

# Copy the rest of the backend code
COPY . .

# Expose the backend port
EXPOSE 3030

# Start the server
CMD ["node", "server.js"]
